apiVersion: v1
kind: Pod
metadata:
  name: pod-vault-wif-aws-ubuntu
  annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/auth-type: "aws"
        vault.hashicorp.com/auth-config-type: "iam"
        vault.hashicorp.com/auth-path: "auth/aws"
        vault.hashicorp.com/role: 'wif-demo-acc-role'
        vault.hashicorp.com/agent-inject-secret-config: 'secret/data/web'
        # Environment variable export template
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/data/web" -}}
            export api_key="{{ .Data.data.foo }}"
          {{- end }}
spec:
  serviceAccountName: wif-demo-acc
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sleep", "999999"]